Repository tmuxinator/tmuxinator, pull requests merged in 2024-02, with the labels that each got.

#890 Update stop command to support project-config and omitting project name
  CHANGELOG.md
  lib/tmuxinator/cli.rb
  spec/lib/tmuxinator/cli_spec.rb
Labels: enhancement

#891 Set pane title if provided in config file
  CHANGELOG.md
  README.md
  lib/tmuxinator/assets/template.erb
  lib/tmuxinator/pane.rb
  lib/tmuxinator/window.rb
  spec/lib/tmuxinator/pane_spec.rb
  spec/lib/tmuxinator/window_spec.rb
Labels: ready, enhancement

#872 Check for github action updates using dependabot
  .github/dependabot.yml
Labels: ready
