Repository tmuxinator/tmuxinator, pull requests merged in 2024-03, with the labels that each got.

#902 fix: Shellescape pane titles
  CHANGELOG.md
  lib/tmuxinator/pane.rb
  spec/lib/tmuxinator/pane_spec.rb
Labels: bug

#892 Add configuration options for pane titles
  CHANGELOG.md
  README.md
  lib/tmuxinator/assets/template.erb
  lib/tmuxinator/project.rb
  spec/lib/tmuxinator/project_spec.rb
Labels: feature

#889 refactor: Replace exists? with exist? for Ruby >= 3.2
  CHANGELOG.md
  lib/tmuxinator/cli.rb
  lib/tmuxinator/config.rb
  spec/lib/tmuxinator/cli_spec.rb
  spec/lib/tmuxinator/config_spec.rb
Labels: bug

#906 Remove mux alias in Bash completion file
  CHANGELOG.md
  completion/tmuxinator.bash
  completion/tmuxinator.fish
Labels: ready, enhancement, breaking-change

#905 chore: Update rubocop to 0.61 for Ruby > 3.0 support
  .codeclimate.yml
  .git-blame-ignore-revs
  .rubocop.yml
  CHANGELOG.md
  Gemfile
  Rakefile
  bin/tmuxinator
  lib/tmuxinator.rb
  lib/tmuxinator/cli.rb
  lib/tmuxinator/config.rb
  lib/tmuxinator/deprecations.rb
  lib/tmuxinator/doctor.rb
  lib/tmuxinator/hooks.rb
  lib/tmuxinator/hooks/project.rb
  lib/tmuxinator/pane.rb
  lib/tmuxinator/project.rb
  lib/tmuxinator/tmux_version.rb
  lib/tmuxinator/util.rb
  lib/tmuxinator/version.rb
  lib/tmuxinator/wemux_support.rb
  lib/tmuxinator/window.rb
  spec/factories/projects.rb
  spec/lib/tmuxinator/cli_spec.rb
  spec/lib/tmuxinator/config_spec.rb
  spec/lib/tmuxinator/doctor_spec.rb
  spec/lib/tmuxinator/hooks/project_spec.rb
  spec/lib/tmuxinator/hooks_spec.rb
  spec/lib/tmuxinator/pane_spec.rb
  spec/lib/tmuxinator/project_spec.rb
  spec/lib/tmuxinator/util_spec.rb
  spec/lib/tmuxinator/wemux_support_spec.rb
  spec/lib/tmuxinator/window_spec.rb
  spec/matchers/pane_matcher.rb
  spec/spec_helper.rb
  tmuxinator.gemspec
Labels: ready, dependencies

#907 chore: Add Ruby 3.2, 3.1 to the test matrix; rm ruby < 3
  .github/workflows/ci.yaml
  CHANGELOG.md
Labels: ready, maintenance
